name: Frontend CI

on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: movie-website

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: movie-website/package-lock.json

      - name: Instalar dependências
        run: npm install
      
      - name: Rodar testes
        env:
          VITE_BASE_QUERY: ${{ secrets.VITE_BASE_QUERY }}
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          VITE_LIST_URL: ${{ secrets.VITE_LIST_URL }}
        run: npm run test

      - name: Build Vite
        run: npm run build

      - name: Rodar Cypress E2E
        env:
          VITE_BASE_QUERY: ${{ secrets.VITE_BASE_QUERY }}
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          VITE_LIST_URL: ${{ secrets.VITE_LIST_URL }}

        run: npx start-server-and-test "vite preview --port 4173" http://localhost:4173 cy:run
